# Dependencies
FROM node:21-alpine3.19 as deps

WORKDIR /usr/src/app

COPY package*.json ./
# COPY package.json ./
# COPY package-lock.json ./

RUN npm install


# Builder - Construye la app
FROM node:21-alpine3.19 as build

WORKDIR /usr/src/app

# Copiar de deps, los modulos de node
COPY --from=deps /usr/src/app/node_modules ./node_modules

# Copiar todo el codigo fuente de la app
COPY . .

RUN npx prisma generate
# RUN npm run test
RUN npm run build

RUN npm ci -f --only=production && npm cache clear --force

# RUN npx prisma migrate deploy


# Crear la imagen final de Docker
FROM node:21-alpine3.19 as prod

WORKDIR /usr/src/app

COPY --from=deps /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app/dist ./dist
COPY --from=build /usr/src/app/prisma ./prisma
COPY --from=build /usr/src/app/node_modules/.prisma ./node_modules/.prisma

ENV NODE_ENV=production

USER node

EXPOSE 3000

CMD [ "node", "dist/main.js" ]